PREFIX : <http://www.exemple.org/>

# 1: Quelle était l'action du joueur "noob" juste avant sa mort durant la session 1 du jeu "LOL"?


# 2: Quels joueurs ont terminé tous les accomplissements du jeu nommé "LOL"?


# 3: Quelle est la moyenne des expériences de tous les joueurs?


# 4: Les joueurs "noob" et "player1" jouent-ils exactement aux meme jeux?


# 5: ...